[package]
name = "conc-map-bench"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
bustle = "0.4.1"
tracing-subscriber = "0.2.4"
num_cpus = "1.13.0"
fxhash = "0.2.1"
dashmap = "3.11.10"
shard_lock = { git = "https://github.com/xacrimon/shard_lock.git" }
parking_lot = "0.10"

[profile.release]
codegen-units = 1
panic = "abort"
lto = true
